#!/bin/bash

# run this script as root
if [ $(id -u) -ne 0 ]; then
  echo "run this script as root"
  exit 1
fi

rmmod lttngprofile 2> /dev/null

set -e

dmesg -c > /dev/null
modprobe lttngprofile
dmesg -c
